name: Test repo

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node
      with: 
        node-version: '20.x'
    - name: Install Deps
      run: yarn install
    - name: Install Deps
      run: yarn run test
