name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      
    - name: Setup Node
      uses: actions/setup-node@v3
      with: 
        node-version: '20.x'
        
    - name: Install Deps
      run: yarn install
      
    - name: Run tests
      run: yarn run test
